server:
  port: 9600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5


spring:
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: wechat-robot
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/robot_cloud?useUnicode=true&autoReconnect=true
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: select 'x'
      validation-query-timeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        slf4j:
          enabled: true
          connection-log-enabled: true
          connection-close-after-log-enabled: true
          connection-commit-after-log-enabled: true
          connection-connect-after-log-enabled: true
          connection-connect-before-log-enabled: true
          connection-log-error-enabled: true
          data-source-log-enabled: true
          result-set-log-enabled: true
          statement-log-enabled: true
        wall:
          enabled: true
          config:
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            #是否允许非以上基本语句的其他语句，缺省关闭，通过这个选项就能够屏蔽DDL
            none-base-statement-allow: false
            #检查UPDATE语句是否无where条件，这是有风险的，但不是SQL注入类型的风险
            update-where-none-check: true
            #SELECT ... INTO OUTFILE 是否允许，这个是mysql注入攻击的常见手段，缺省是禁止的
            select-into-outfile-allow: false
            #是否允许调用Connection.getMetadata方法，这个方法调用会暴露数据库的表信息
            metadata-allow: true
            #允许多条sql一起执行
            multiStatementAllow: true
          log-violation: true
          #对被认为是攻击的SQL抛出SQLExcepton
          throw-exception: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        #你可以配置principalSessionName，使得druid能够知道当前的cookie的用户是谁
        #principal-cookie-name: admin
        #你可以配置principalSessionName，使得druid能够知道当前的session的用户是谁
        #principal-session-name: admin
        #设置profileEnable能够监控单个url调用的sql列表。
        profile-enable: true
        #session统计功能
        session-stat-enable: false
        #最大session数
        session-stat-max-count: 100000
      stat-view-servlet:
        #          allow: ${GATEWAY_HOST:172.26.114.241}
        enabled: true
        login-username: admin
        login-password: luo19950105
        url-pattern: /druid/*
        #允许清除记录
        reset-enable: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.cloud.pojo.article
  global-config:
    id-type: 5
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000

wechat:
  ua: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
  url:
    entry: https://wx.qq.com/
    login-base: https://login.weixin.qq.com
    path-base: /cgi-bin/mmwebwx-bin
    uuid: ${wechat.url.login-base}/jslogin?appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&_=%s
    qrcode: ${wechat.url.login-base}/qrcode
    login: ${wechat.url.login-base}${wechat.url.path-base}/login?loginicon=true&uuid=%s&tip=0&r=%s&_=%s
    init: ${wechat.url.path-base}/webwxinit?r=%s&pass_ticket=%s
    statreport: ${wechat.url.entry}${wechat.url.path-base}/webwxstatreport?fun=new
    status-notify: ${wechat.url.path-base}/webwxstatusnotify?pass_ticket=%s
    sync-check: ${wechat.url.path-base}/synccheck
    sync: ${wechat.url.path-base}/webwxsync?sid=%s&skey=%s&pass_ticket=%s
    get-contact: ${wechat.url.path-base}/webwxgetcontact?r=%s&seq=%s&skey=%s&pass_ticket=%s&lang=zh_CN
    send-msg: ${wechat.url.path-base}/webwxsendmsg?pass_ticket=%s
    upload-media: ${wechat.url.path-base}/webwxuploadmedia?f=json
    get-msg-img: ${wechat.url.path-base}/webwxgetmsgimg?&MsgID=%s&skey=%s&pass_ticket=%s
    get-voice: ${wechat.url.path-base}/webwxgetvoice
    get-video: ${wechat.url.path-base}/webwxgetvideo
    push-login: ${wechat.url.path-base}/webwxpushloginurl
    logout: ${wechat.url.path-base}/webwxlogout?redirect=1&type=1&skey=%s
    batch-get-contact: ${wechat.url.path-base}/webwxbatchgetcontact?type=ex&r=%s&pass_ticket=%s
    op-log: ${wechat.url.path-base}/webwxoplog
    verify-user: ${wechat.url.path-base}/webwxverifyuser?pass_ticket=%s
    get-media: ${wechat.url.path-base}/webwxgetmedia
    create-chatroom: ${wechat.url.path-base}/webwxcreatechatroom?r=%s
    delete-chatroom-member: ${wechat.url.path-base}/webwxupdatechatroom?fun=delmember
    add_chatroom-member: ${wechat.url.path-base}/webwxupdatechatroom?fun=addmember
