server:
  port: 9900

spring:
  application:
    name: web-gateway
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: luo19950105.
    timeout: 10000ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    api-blog-server:
      path: /blog/**
      serviceId: blog-server
    api-user-server:
      path: /user/**
      serviceId: user-server

blog-server:
  ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 15000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: true

user-server:
  ribbon:
    ReadTimeout: 30000
    ConnectTimeout: 15000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000
