server:
  port: 9400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5


spring:
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: wechat-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000

wx:
  mp:
    configs:
      - app-id: wxe6f2002aa38e4f49
        secret: 177ed3a30dec3e8648b9315f66dbce41
        token: __token__
        encoding-aes-key: KsTzc9K22LX6BoOtmYCC6jP0mg63ITbrHmxd9ZTog3j
      - app-id: 22
        secret: 22
        token: 22
        encoding-aes-key: 22

