server:
  port: 9400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 5


spring:
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: wechat-server
#  redis:
#    database: 0
#    host: 39.108.235.243
#    port: 6379
#    password: luo19950105.
#    timeout: 10s
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 600000

wx:
  mp:
    configs:
      - app-id: 11
        secret: 11
        token: 11
        encoding-aes-key: 11
      - app-id: 22
        secret: 22
        token: 22
        encoding-aes-key: 22

