server:
  port: 9100

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:9100/eureka/
  instance:
    hostname: peer1
    prefer-ip-address: false
    appname: ${spring.application.name}
    instanceId: ${eureka.instance.hostname}:${server.port}

spring:
  application:
    name: eureka-server

